version: 2
jobs:
  build:
    docker:
      - image: macnicadevops/cci-build-aws:1.0
    environment:
      repo: docker-local
    steps:
      - checkout
      - setup_remote_docker
            
      - run:
          name: Build Image
          command: |
            docker build -t $jfqdn2"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: Configure JFrog CLI 
          command: |
            /jfrog rt config --user=$user --password=$password --insecure-tls --url="https://"$jfqdn2"/artifactory" $jid
      - run:
          name: JFrogCLI Artifact publish, scan and promote
          command: |
           /jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM 
           /jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM 
           /jfrog rt dp $jfqdn2"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM $repo --build-name=$CIRCLE_PROJECT_REPONAME --build-number=$CIRCLE_BUILD_NUM --insecure-tls
           /jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM --insecure-tls
           /jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM --insecure-tls
           /jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM $repo --insecure-tls
