version: 2
jobs:
  build:
    docker:
      - image: macnicadevops/cci-build-aws:1.0
    environment:
      repo: docker-local
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Image
          command: |
            sudo echo '{"insecure-registries" : ["35.192.149.57"]}' > /etc/docker/daemon.json
            docker build -t $repo"."$jfqdn2"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: Configure JFrog CLI 
          command: |
            /jfrog rt config --user=$user --password=$password --url="http://"$jfqdn2"/artifactory" $jid
      - run:
          name: JFrogCLI Artifact publish, scan and promote
          command: |
           /jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM $repo
