version: 2
jobs:
  build:
    docker:
      - image: macnicadevops/cci-build-aws:1.0
    environment:
      repo: docker-local
    steps:
      - checkout
      - setup_remote_docker
            
      - run:
          name: Build Image
          command: |
            docker build -t $repo"."$jfqdn2"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: Configure JFrog CLI 
          command: |
            /jfrog rt config --user=$user --password=$password --insecure-tls --url="https://"$jfqdn2"/artifactory" $jid
      - run:
          name: JFrogCLI Artifact publish, scan and promote
          command: |
           /jfrog rt bce --insecure-tls $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bag --insecure-tls $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bp --insecure-tls $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bs --insecure-tls $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bpr --insecure-tls $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM $repo
